language: python

python:
  - "3.6"

before_install:
 - "sudo apt-get install autoconf automake autotools-dev"
 - "sudo apt-get install asciidoc xsltproc"
 - "autoreconf -vif"

install:
  - "pip install -r requirements.txt"

script:
 - "./autogen.sh"
 - "./configure"
 - "make dist"
 - "make check -j5"

